// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr2nBekisDbNDGYWx18DezZLfpbnNmC5E',
    appId: '1:455210684738:web:7a6271aaf10966207c78db',
    messagingSenderId: '455210684738',
    projectId: 'learn-app-b80e1',
    authDomain: 'learn-app-b80e1.firebaseapp.com',
    storageBucket: 'learn-app-b80e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACXpQGmLrU44_sFKlEC9zBAA7Krnhy4E',
    appId: '1:455210684738:android:c0c281c5326143a77c78db',
    messagingSenderId: '455210684738',
    projectId: 'learn-app-b80e1',
    storageBucket: 'learn-app-b80e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJFQ9W9h1D8kenJ4pH6yuu-47FISSRlrk',
    appId: '1:455210684738:ios:87abbdd76af4957d7c78db',
    messagingSenderId: '455210684738',
    projectId: 'learn-app-b80e1',
    storageBucket: 'learn-app-b80e1.appspot.com',
    iosClientId: '455210684738-g1iatc7r6huqaueue6o5vn99pjtu98pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJFQ9W9h1D8kenJ4pH6yuu-47FISSRlrk',
    appId: '1:455210684738:ios:87abbdd76af4957d7c78db',
    messagingSenderId: '455210684738',
    projectId: 'learn-app-b80e1',
    storageBucket: 'learn-app-b80e1.appspot.com',
    iosClientId: '455210684738-g1iatc7r6huqaueue6o5vn99pjtu98pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearn',
  );
}
